language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PINS="mirage-dns:. dns-async:. dns-lwt:. dns-lwt-unix:."
   - PACKAGE="dns"
   - DEPOPTS="mirage-dns dns-async dns-lwt dns-lwt-unix"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03
   - DISTRO=debian-testing OCAML_VERSION=4.04
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03
   - DISTRO=alpine OCAML_VERSION=4.04
